Repository amaranth-lang/rfcs, pull requests merged in 2024-02, with the labels that each got.

#46 Add RFC for `Shape.cast(range(1))` change.
  text/0046-shape-range-1.md
Labels: area:core

#27 Testbench functions for the simulator
  text/0027-simulator-testbenches.md
Labels: area:core

#45 Move `hdl.memory` to `lib.memory` and extend it
  text/0040-arbitrary-memory-shape.md
  text/0045-lib-memory.md
Labels: area:core

#42 Add an RFC for `Const` from shape-castable.
  text/0042-const-from-shape-castable.md
Labels: area:core

#16 A CSR register API for amaranth-soc
  text/0016-soc-csr-regs.md
Labels: area:soc

#47 RFC #27: Amend to deprecate `add_sync_process` rather than `add_process`
  text/0027-simulator-testbenches.md
Labels: meta:nominated, area:core

#43 Rename `reset=` to `init=`
  text/0043-rename-reset-to-init.md
Labels: area:core
